{-|
Module      : Test_SDP
Description : This module contains property-based tests for the SDP model.
Tool        : quickCheck

Key Components:
- `Action` and `State`: Data types representing possible actions and states in the SDP model.
- Arbitrary Instances: Instances of `Arbitrary` for `Action` and `State` to enable random generation of test cases.
- `dummyProb2`: A helper function to create a normalized probability distribution over a list of elements.
-}
module Test_SDP where

import Test.QuickCheck
import SDPCompute
import Prob
import Data.Map (Map)
import qualified Data.Map as Map

data Action = Start | Delay deriving (Show, Eq, Enum, Ord, Read)
data State  = S1 | S2 | S3 deriving (Show, Eq, Enum, Ord, Read)

instance Arbitrary Action where
    arbitrary = elements [Start, Delay]

instance Arbitrary State where 
    arbitrary = elements [S1, S2, S3]

dummyProb2 :: [a] -> Prob a
dummyProb2 xs = normalize (Prob [(x, 1.0) | x <- xs])


-- | A dummy SDP for testing purposes.
testSDP :: SDP State Action
testSDP = SDP {
    reward  = \_ _ _ _ -> 1.0,
    next    = \_ _ _   -> dummyProb2 [S1, S2, S3],
    actions = \_ s -> case s of
        S1 -> [Start, Delay]
        S2 -> [Start, Delay]
        S3 -> [Start, Delay],
    states  = \_       -> [S1, S2, S3]
}

-- =====================================================================
-- Test val
-- =====================================================================

-- | Test that when the policy sequence is empty, the value function `val` returns 0.
prop_valEmptyPolicy :: Int -> State -> Property
prop_valEmptyPolicy t x =
    t  >= 0 ==> val testSDP t [] x == 0


-- | Test that the length of the policy sequence generated by `bi` matches the specified horizon `n`.
prop_biLength :: Int -> Int -> Property
prop_biLength t n = (n >= 0) ==> length (bi testSDP t n) == n


-- | Checks that the value function `val` always returns a non-negative value for any generated policy sequence.
prop_valNonNegative :: Int ->  State -> Property
prop_valNonNegative t x =
    forAll (choose (0, 8)) $ \t ->  -- Generate t between 0 and 8
    forAll (choose (1, 8)) $ \n ->  -- Generate n between 1 and 10
    let policySeq = bi testSDP t n  
    in val testSDP t policySeq x >= 0


-- | Test that a longer policy sequence is at least as good as the original sequence (geq).
prop_longerPolicyBetterOrEqual :: Int ->  State -> Property
prop_longerPolicyBetterOrEqual t x =
    forAll (choose (0, 8)) $ \t ->  -- Generate t between 0 and 8
    forAll (choose (1, 8)) $ \n ->  -- Generate n between 1 and 10 
    let ps = bi testSDP t n
    in
        not (null ps) ==> 
        let v1 = val testSDP t ps x
            v2 = val testSDP t (ps ++ [last ps]) x
        in v2 >= v1

-- =====================================================================
-- Test bi
-- =====================================================================

-- | Property: bi should return an empty policy sequence when n <= 0, regardless timestep (value of t)
prop_biEmptyPolicy ::  Int -> Property
prop_bi_empty_policy t = 
    forAll (choose (0, 8)) $ \t ->
    let ps = bi testSDP t 0
    in ps == []

-- | The sequence produced should have exactly n elements.
prop_biCorrectLength :: Int -> Property
prop_bi_correct_length t =
    forAll(choose (0, 8)) $ \t ->
    forAll(choose (1, 8)) $ \n ->
    let ps = bi testSDP t n
    in length(ps) == n

-- | Test that every element of the sequence should be a valid Policy, meaning: It defines an action for every reachable state at that time t.
prop_biCorrectElements :: Property
prop_bi_correct_elements =
  forAll (choose (0, 8)) $ \t ->
  forAll (choose (1, 8)) $ \n ->
    let ps = bi testSDP t n
        allStates = states testSDP t 
    in all (\p -> all (`Map.member` p) allStates) ps



----------------------------------------------------------------------

testVal :: IO()
testVal = do
    quickCheck prop_biLength
    quickCheck prop_valEmptyPolicy
    quickCheck prop_valNonNegative
    quickCheck prop_longerPolicyBetterOrEqual

testBi :: IO()
testBi = do
    quickCheck prop_BiEmptyPolicy
    quickCheck prop_BiCorrectLength
    quickCheck prop_BiCorrectElements 

testAll :: IO ()
testAll = do
    testVal



runBi :: Int -> Int -> PolicySeq State Action
runBi t n = bi testSDP t n